{% set name = "click-didyoumean" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f184f0d851d96b6d29297354ed981b7dd71df7ff500d82fa6d11f0856bee8035

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  host:
    - pip
    - python
  run:
    - click
    - python

test:
  imports:
    - click_didyoumean

about:
  home: https://github.com/timofurrer/click-didyoumean
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Enable git-like did-you-mean feature in click.

extra:
  recipe-maintainers:
    - duncanmmacleod
